#weapon=1
Name=Glock
ImagePath=assets/weapons/glock/hold.png
ShopImage=assets/weapons/glock/preview.png
RouteX=4
RouteY=3
Type=101
Magazine=15
ReloadTime=30
Diameter=9
Up=30
Damage=20
Running=0
Speed=600
Price=0
Sound=assets\weapons\glock\sounds\glock18-2.wav

#weapon=2
Name=Desert Eagle
ImagePath=assets/weapons/desert_eagle/hold.png
ShopImage=assets/weapons/desert_eagle/preview.png
RouteX=3
RouteY=2
Type=101
Magazine=8
ReloadTime=30
Diamter=12.7
Up=30
Damage=60
Running=0
Speed=60
Price=0
Sound=assets\weapons\desert_eagle\sounds\deagle-2.wav
Play1=1
Sound1=assets\weapons\desert_eagle\sounds\de_clipout.wav
Play2=15
Sound2=assets\weapons\desert_eagle\sounds\de_clipin.wav
Play3=30
Sound3=assets\weapons\desert_eagle\sounds\de_deploy.wav

#weapon=3
Name=AK47
ImagePath=assets/weapons/ak47/hold.png
ShopImage=assets/weapons/ak47/preview.png
RouteX=2
RouteY=1
Type=101
Magazine=30
ReloadTime=30
Diameter=7.62
Up=-0
Damage=50
Running=1
Speed=600
Price=0
Sound=assets\weapons\ak47\sounds\1.wav
Play1=1
Sound1=assets\weapons\ak47\sounds\clipout.wav
Play2=15
Sound2=assets\weapons\ak47\sounds\clipin.wav
Play3=30
Sound3=assets\weapons\ak47\sounds\boltpull.wav

#weapon=4
Name=Grenade on AK47
ImagePath=assets/weapons/ak47_grenade_launcher/hold.png
ShopImage=assets/weapons/ak47_grenade_launcher/hold.png
RouteX=2
RouteY=1
Type=102
Magazine=1
ReloadTime=30
Diameter=40
Damage=100
Ruuning=1
Speed=60
Price=0

#weapon=5
Name=AWM
ImagePath=assets/weapons/awm/hold.png
ShopImage=assets/weapons/awm/preview.png
RouteX=3
RouteY=1
Type=101
Magazine=10
ReloadTime=30
Diameter=7.62
Up=30
Damage=100
Running=0
Speed=60
Price=0
Sound=assets\weapons\awm\sounds\awm1.wav
Play1=1
Sound1=assets\weapons\awm\sounds\awm_clipout.wav
Play2=15
Sound2=assets\weapons\awm\sounds\awm_clipin.wav
Play3=30
Sound3=assets\weapons\awm\sounds\awm_deploy.wav


#weapon=6
Name=AUG
ImagePath=assets/weapons/aug/hold.png
ShopImage=assets/weapons/aug/preview.png
RouteX=3
RouteY=2
Type=101
Magazine=30
ReloadTime=40
Diameter=5.56
Up=-0
Damage=30
Running=1
Speed=800
Price=0
Sound=assets\weapons\aug\sounds\aug-1.wav
Play1=1
Sound1=assets\weapons\aug\sounds\aug_boltslap.wav
Play2=15
Sound2=assets\weapons\aug\sounds\aug_clipout.wav
Play3=30
Sound3=assets\weapons\aug\sounds\aug_clipin.wav
Play4=40
Sound4=assets\weapons\aug\sounds\aug_boltpull.wav

#weapon=7
Name=M249
ImagePath=assets/weapons/m249/hold.png
ShopImage=assets/weapons/m249/hold.png
RouteX=3
RouteY=3
Type=101
Magazine=100
ReloadTime=60
Diameter=5.56
Up=-0
Damage=20
Running=1
Speed=750
Price=0
Sound=assets\weapons\m249\sounds\m249-2.wav
Play1=1
Sound1=assets\weapons\m249\sounds\m249_coverup.wav
Play2=15
Sound2=assets\weapons\m249\sounds\m249_boxout.wav
Play3=25
Sound3=assets\weapons\m249\sounds\m249_chain.wav
Play4=50
Sound4=assets\weapons\m249\sounds\m249_boxin.wav
Play5=60
Sound5=assets\weapons\m249\sounds\m249_coverdown.wav
